name: Red Coat Diaries
favicon: null
layout_spectrum: 0.9224379004444927
typography_spectrum: 0.6180402475874871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8f5fb'
    - '#952121'
    - '#7b602b'
    - '#76b4d9'
    - '#000000'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
