analytics: {}
color:
  brandColors:
    - '#A8B8C0'
    - '#706028'
    - '#6088A0'
    - '#902020'
    - '#D0E8F0'
  brandStrength: 1
  lightness: 0.762387
  rhythmicContrast: 0.862612
  saturation: 0.748873
cta: {}
layout_spectrum: 0.917792
name: Red Coat Diaries
opengraph: {}
purpose: []
typography_spectrum: 0
